# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-credential-org" do
  name "git-credential-org"
  desc "Git credential helper that resolves credentials by organization namespace"
  homepage "https://github.com/imcitius/git-credentials-org"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-credential-org"

  on_macos do
    on_intel do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credential-org_#{version}_darwin_amd64.tar.gz"
      sha256 "0f64d9cc9cb476da36496eba17e1cd81e71f1a8e73bea501b5bdf58ae606c3b7"
    end
    on_arm do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credential-org_#{version}_darwin_arm64.tar.gz"
      sha256 "385ce4e986c5b15e166b158caff1b11d57352315112ba28f4a111bf591736798"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credential-org_#{version}_linux_amd64.tar.gz"
      sha256 "447895f86180c6633b13ab672b2da20a8a689a2b531bf3e0a1d2073ae18d9fa6"
    end
    on_arm do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credential-org_#{version}_linux_arm64.tar.gz"
      sha256 "e84a9b8c8754529e7db8e534067a11635d636c56ecc6c7282c195c26177087e9"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-credential-org"]
  end

  # No zap stanza required
end
