# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-credentials-org" do
  name "git-credentials-org"
  desc "Git credential helper that resolves credentials by organization namespace"
  homepage "https://github.com/imcitius/git-credentials-org"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-credentials-org"

  on_macos do
    on_intel do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credentials-org_#{version}_darwin_amd64.tar.gz"
      sha256 "8f37cb9221e33202e8d75f731a41ff982800952317dcc921b65a5ad739a91ce9"
    end
    on_arm do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credentials-org_#{version}_darwin_arm64.tar.gz"
      sha256 "d1089e766b4c632828b88bfdee11c6db0b47ec622005210ecef0c143aa7df683"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credentials-org_#{version}_linux_amd64.tar.gz"
      sha256 "00ac1f016084c6c5652810c0e639628877826b249fb0b6b820d7deab0a679a75"
    end
    on_arm do
      url "https://github.com/imcitius/git-credentials-org/releases/download/v#{version}/git-credentials-org_#{version}_linux_arm64.tar.gz"
      sha256 "2d7ba8e336b6feddbf2b22c1a04961adb689564a8ba2804a959a4e2027fec572"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-credentials-org"]
  end

  # No zap stanza required
end
