# This file was generated by GoReleaser. DO NOT EDIT.
cask "tgsieve" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d9c3ba988beb9c51943ef2c8cd993ca7fae31db4fd340f49b6e6e8a8198d976a"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0756b86f072a8789b76997d6cb7872b50c9656dc3dba21e8570c7b1ebc1a9ac3"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f98012a111c79f6b58a6a6c203c193355a230899132b3802acd696d6488dc84"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "178b7b9e5b55d1530973786d0e33889c2eaad14af4befbf916295cb52812eaee"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tgsieve"
  desc "Terragrunt plans without the wall of text"
  homepage "https://github.com/imcitius/tgsieve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tgsieve"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tgsieve"]
    end
  end

  # No zap stanza required

end
