# This file was generated by GoReleaser. DO NOT EDIT.
cask "tgsieve" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "0dabb4b2f0c1af7c4041319a3a1c625764ad0daee0279be84b00d7a308f152a4"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "91fd8262135424b164d74b0af2f685ff99e59e964932ba2f0e4cd1c8316a8ad8"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90766b78dc48a64880a87be3c663df7f1766d06cf86a7e5c8bf07db818063749"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01ea0fc246479f4f2c60aae620581389a7bfbb40070c372e0b9b6b76fba21442"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tgsieve"
  desc "Terragrunt plans without the wall of text"
  homepage "https://github.com/imcitius/tgsieve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tgsieve"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tgsieve"]
    end
  end

  # No zap stanza required

end
