# This file was generated by GoReleaser. DO NOT EDIT.
cask "tgsieve" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "37a59fc9d17b61d73a0047ed98ec2c695712ae55c589cff7ea4d9c35d4962007"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "82c4683e106b5572a0f0bb3e85ae56dcc41c1782e660183a7acbac0931d82250"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bf30193e7dc0abf27e1c4b9d6eab4ce568176b0cbb3c287d01d235418d3b938e"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "15f2460817888c7e04d246f9ad9a25179db3fcf82c6a40d5b1ccc58508d48182"
      url "https://github.com/imcitius/tgsieve/releases/download/v#{version}/tgsieve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tgsieve"
  desc "Terragrunt plans without the wall of text"
  homepage "https://github.com/imcitius/tgsieve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tgsieve"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tgsieve"]
    end
  end

  # No zap stanza required

end
